name: Merge Tag to Backup Branch

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      tag:
        description: 'Tag to merge to backup branch (e.g., v1.0.0)'
        required: true

jobs:
  merge_tag:
    name: Merge Tag to Backup Branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Create Temporary Branch
      run: | 
        git fetch --tags
        git checkout -b temp ${{ github.event.inputs.tag }}

    - name: Merge Temporary Branch to Backup Branch
      run: |
        git checkout back_up
        git merge --no-ff --no-edit temp

    - name: Push Changes to Backup Branch
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Tag on Backup Branch
      run: git tag b-${{ github.event.inputs.tag }} back_up

    - name: Push Tag to GitHub
      uses: ad-m/github-push-action@v0.6.0
      with:
        tags: b-${{ github.event.inputs.tag }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete Temporary Branch
      run: git branch -d temp
