name: Merge Tag into Branch

on:
  workflow_dispatch :
    inputs:
        tag_name:
          description: 'Provide the name of the tag to merge'
          required: true

jobs:
  MergeTag:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git first
      run: |
        git config --global user.email "actions@example.com"
        git config --global user.name "GitHub Actions"
    

    - name: Checkout repository (in the current branch)
      uses: actions/checkout@v3

    - name: Merge tag into branch (here, it is back_up branch)
      run: |
        git fetch --tags
        git checkout back_up
        git merge ${{ github.event.inputs.tag_name }}
        git tag -a "b-${{ github.event.inputs.tag_name }}" -m "${{ github.event.pull_request.body }}"
        git push origin back_up
        git push origin "b-${{ github.event.inputs.tag_name }}"
